name: Build and Release Windows EXE

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  setup:
    name: Install & Cache Dependencies
    runs-on: windows-latest
    outputs:
      python-version: "3.10"
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  check:
    name: Lint / Syntax Check
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Check syntax
        run: python -m py_compile main.py

  build:
    name: Build EXE
    needs: check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconsole --onefile --name PDFReader `
            --collect-submodules pandas `
            --collect-submodules numpy `
            --collect-all pdfplumber `
            --collect-all tkinterdnd2 `
            --hidden-import openpyxl.styles `
            --hidden-import openpyxl.formatting.rule `
            --hidden-import tkinter.ttk `
            --hidden-import tkinter `
            main.py

      - name: Verify EXE exists
        shell: pwsh
        run: |
          if (!(Test-Path "dist\\PDFReader.exe")) {
            Write-Error "EXE not found."
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-reader-exe
          path: dist/PDFReader.exe

  test:
    name: Launch EXE and Monitor
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download built EXE
        uses: actions/download-artifact@v4
        with:
          name: pdf-reader-exe
          path: dist

      - name: Test EXE
        shell: pwsh
        run: |
          try {
            $proc = Start-Process -FilePath "dist\\PDFReader.exe" -PassThru
            Start-Sleep -Seconds 5
            if ($proc.HasExited) {
              Write-Error "EXE exited early with code $($proc.ExitCode)"
              exit $proc.ExitCode
            } else {
              Stop-Process -Id $proc.Id
              Write-Output "EXE launched and stayed alive for 5 seconds."
            }
          } catch {
            Write-Error "EXE failed to launch"
            exit 1
          }

  release:
    name: Publish GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf-reader-exe
          path: ./release

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: PDFReader ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release/PDFReader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
